services:
  - type: web
    name: hk-cat-cafe
    env: docker
    plan: free
    branch: main

    autoDeploy: true

    envVars:
      - key: APP_NAME
        value: hk-cat-cafe

      - key: APP_ENV
        value: production

      - key: APP_KEY
        sync: false

      - key: APP_DEBUG
        value: false

      - key: APP_URL
        value: https://hk-cat-cafe.onrender.com

      - key: LOG_CHANNEL
        value: stderr

      # DB設定
      - key: DB_CONNECTION
        value: pgsql

      - key: DB_HOST
        fromDatabase:
          name: hk-cat-cafe-db
          property: host

      - key: DB_PORT
        fromDatabase:
          name: hk-cat-cafe-db
          property: port

      - key: DB_DATABASE
        fromDatabase:
          name: hk-cat-cafe-db
          property: database

      - key: DB_USERNAME
        fromDatabase:
          name: hk-cat-cafe-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: hk-cat-cafe-db
          property: password

      # メール（本番はログ出力）
      - key: MAIL_MAILER
        value: log

databases:
  - name: hk-cat-cafe-db
    plan: free
